import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ProfileProvider from "./core/providers/ProfileProvider";
import Sidebar from "./components/dashboard/SideBar";
import DashHeader from "./components/DashHeader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="h-screen flex flex-col">
        <ProfileProvider>
          <div className="flex flex-row flex-1">
           <Sidebar /> 
           <div className="flex flex-col flex-1 w-full">
           <DashHeader />
           <div className="flex-1 overflow-auto">
            {children}
            </div>
            </div>
          </div>
        </ProfileProvider>
      </body>
    </html>
  );
}